#!/usr/bin/env bash

set -xeo pipefail

# export PATH="$INSTALL_DIR/bin:$PATH"

# Install jupyterlab extensions
# source activate dcpy
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/toc \
                             dask-labextension \
			     @pyviz/jupyterlab_pyviz \
			     @bokeh/jupyter_bokeh
                             

jupyter labextension update --all

conda uninstall --force --offline xarray
cd $HOME/python/xarray && pip install -e .
