name: base
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - nb_conda_kernels
  - emacs
  - fzf
  - gh
  - jupyter-forward
  - dask_labextension
  - jupyterlab_code_formatter
  - jupyter-server-proxy
  - ipympl
  - ipywidgets
  - black
  - isort
  - flake8
  - pre-commit
  - mypy
  - pyflakes
  - pycodestyle
  - pip
  - pip:
    - python-lsp-server
    - python-lsp-black
    - pyls-flake8
    - mypy-ls
    - pyls-isort
