name: base
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyter-server-proxy
  - jupyterlab-deck
  - jupyterlab-lsp
  - jupyterlab-myst
  - jupyterlab_widgets
  - nb_conda_kernels
  # - emacs
  # - fzf
  - gh
  # - jupyter-forward
  - zoxide
  - git-delta
  - cookiecutter
  - cruft
  - python-lsp-server
  - python-lsp-ruff
  - python-lsp-black
  - mypy-ls
  - pyls-isort
  - nodejs
  - nco
  - dask_labextension
  - ipympl
  - ipywidgets
  - ipyaggrid
  - ipytree
  - pre-commit
  - ruff
  - black
  - isort
  - flake8
  - mypy
  - proselint
  - shellcheck
  # - lftp
  - aspell
  - jedi
  - numpydoc
  - pyviz_comms
  - pip
  - versioneer
  - poetry
  - eccodes
  # cloudy
  - awscli
  - google-cloud-sdk
  # - s5cmd  # not on osx-arm
