name: base
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - jupyterlab
  - nb_conda_kernels
  # - emacs
  - fzf
  - gh
  - jupyter-forward
  - zoxide
  - cookiecutter
  - cruft
  - dask_labextension
  - jupyterlab_code_formatter
  - jupyter-server-proxy
  - jupyterlab-deck
  - jupyterlab-lsp
  - jupyterlab-myst
  - jupyterlab_widgets
  - python-lsp-server
  - nodejs
  - nco
  - ipympl
  - ipywidgets
  - ipyaggrid
  - black
  - isort
  - flake8
  - pre-commit
  - mypy
  - proselint
  - shellcheck
  - lftp
  - aspell
  - jedi
  - numpydoc
  - pyviz_comms
  - pip
  - versioneer
  - pip:
    - python-lsp-black
    - python-lsp-ruff
    - mypy-ls
    - pyls-isort
