name: base
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - jupyterlab
  - nb_conda_kernels
  - emacs
  - fzf
  - gh
  - jupyter-forward
  - zoxide
  - cookiecutter
  - cruft
  - dask_labextension
  - jupyterlab_code_formatter
  - jupyter-server-proxy
  - jupyterlab-lsp
  - python-lsp-server
  - nodejs
  - ipympl
  - ipywidgets
  - black
  - isort
  - flake8
  - pre-commit
  - mypy
  - proselint
  - shellcheck
  - lftp
  - aspell
  - pyflakes
  - pycodestyle
  - pyviz_comms
  - pip
  - pip:
    - jupyterlab-myst
    - python-lsp-black
    - python-lsp-ruff
    - pyls-flake8
    - mypy-ls
    - pyls-isort
