channels:
  - conda-forge
  - pyviz
dependencies:
  - ipdb
  - snakeviz
  - snoop
  - line_profiler
  - memory_profiler
  - ipykernel
  - ptime
  - watermark
  - python-graphviz
  - dask-labextension  # needed for cool "launch dashboard" button
  - pip:
      - icecream
